### ISSUE TITLE
Catlett Menu Board Questions

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/dining.uiowa.edu#16]
> What is up with the BYO Omelet and eggs, egg beaters and quinoa for a base?

Add a new subqueue: `Choose a base: eggs, egg beaters, quinoa.`

**Comment by adamdelaney** [comment]
> Who is in charge of imaging the compute sticks? What is the hardware stack?
Brandon Mills

**Comment by adamdelaney** [comment]
> What are the lat/lon points of the hall?

We've added the lat long, but we should check into how Google Maps labels things.

**Comment by adamdelaney** [comment]
> What thumbnail/header images are to be used for the location?

UHD will add this in production.

**Comment by adamdelaney** [comment]
> Does build your own omelet ingredients need nutritional indicators?

UHD will get back to us on this,

**Comment by richardbporter** [comment]
💯
