### ISSUE TITLE
Signage debug query parameters breaks slideshow templating

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/dining.uiowa.edu#20]
We are using $location . '-' . $mode . '-' . $display, variables to get the node title of the template and slideshow images, however when entering in debug mode, these variables are not set correctly.

For example:
- $location == catlett
- $mode == debug: 1500526800 l
- $display == sprouts-2

**Comment by richardbporter** [comment]
Resolved but you have to pass in the full word now, e.g. mode=lunch.
