### ISSUE TITLE
Additional menu stucture

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/dining.uiowa.edu#21]
- Can we add a Delights section to breakfast?
  - Yes we need to add a delights for breakfast for web display.
- For the BYO Deli Sandwich, can we add a section Sprouts-Paninis-Build your own? Same for the BYO Yogurt Parfait?
  - We are going to build 3 more Items/ingredients like sizzling salads
  - Build your own Sandwich
  - Build your own Parfait
  - Fruit.

I believe Delights will be added as a station to breakfast and the other items will be for the menu boards only.

- [x] Add delights breakfast field

- [x] Add Flavors title field

- [x] Add BYO Sandwich to sprouts 2

- [x] Add BYO Parfait to sprouts 2

- [x] Add Fruit to sprouts 2

**Comment by richardbporter** [comment]
Break out into special fields for sprouts display: panini side.
