### ISSUE TITLE
disable auto refresh on compute sticks

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/dining.uiowa.edu#35]
Talk to Isaac

**Comment by adamdelaney** [comment]
I emailed Isaac and Brandon on 7-26-2017

**Comment by adamdelaney** [comment]
I had a phone conversation with Isaac about why the compute sticks were refreshing. The short of it is that the compute sticks auto correct, meaning it will ensure that Chrome is running in Kiosk mode and is pointing at the correct URL. This is managed in Active Directory. Al Raymond, Jessica Church and Isaac Podolefsky all have access to update this information. Once this is in production the refresh issue should not be a problem.
