### ISSUE TITLE
Allow webmasters to clear the dining hours cache

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/dining.uiowa.edu#4]
We have told Amanda if there is a critical hours change for a location to save the location node after 15-20 minutes have passed (to give time for the hours change to work from O365 to the hours API).

I don't recall how long we're caching hours in the site, but on node update, we should clear the dining hours cache so we have a regenerated set of hours when the varnish cache is rebuilt.

**Comment by richardbporter** [comment]
Relying on editors to time content changes could be, um, unreliable. :) 

Exposing a button to clear the dining hours cache could let them see if the change happens while authenticated. External cache is another issue.
