### ISSUE TITLE
Dining updates Summer 2019

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/dining.uiowa.edu#70]
## Requirements
- Homepage Cards: ITS will implement the page building tools for basic pages.
- Page Sections: ITS will implement the page building tools for basic pages.
- Accordion Sections: ITS will implement the page building tools for basic pages.
- Contact Cards: ITS will investigate how housing.uiowa.edu implements people and will implement it on the dining site.
- Maps Integration: Done.
- Header Slideshow: ITS will investigate how housing.uiowa.edu implements banner slideshow and will implement it on the dining site.
- Frontpage search for food: Not now but, this could be implemented, using a taxonomy and connecting it to locations. This would not include retail menu items because those are currently PDFs.
- Webform: Done.
- ~~Location filters: UHD will determine which filters they want for https://dining.uiowa.edu/locations. ITS will add new fields to locations if needed and add filters similar to how: https://housing.uiowa.edu/residence-halls works.~~
- Meeting Scheduler for students: This is done but unpublished in production see: https://dining.uiowa.edu/dietitian-appointment.
- Dietary accommodations form: ITS will investigate how PCI compliance and sensitive webform data can be handled.
- Homepage promo scheduling: ITS will implement the page building tools, no scheduling at this time.
- Allow previous days in menu date picker: ITS will investigate if this is possible using the CBORD integration.
- Videos: Done, you can embed videos using our WYSIWYG.
- Remove news: ITS will remove the news content and content type.
- Location theming: ITS will align location pages (full node) to visually align with housing residence halls: see: https://housing.uiowa.edu/residence-halls/burge-hall
- Retail menus: UHD and ITS will investigate if retail menus are available in CBORD. If not, ITS can investigate if catering menus can be ported to dining, see: https://catering.uiowa.edu/menus/breakfast.

## Timeline
UHD would like the work done by Summer 2019.

## Contacts
- Megan Yoder
- Anne Matthes

## Developers
- Richard Porter

**Comment by richardbporter** [comment]
Lets split these out into individual issues for what is left. I'll start and we can just close ones that are already done.
