### ISSUE TITLE
Unpublish all blog content

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/dining.uiowa.edu#80]
Remove the news content and content type.

**Comment by richardbporter** [comment]
Example:  https://github.com/ITS-UofIowa/dining.uiowa.edu/blob/master/modules/custom/dining_core/dining_core.install#L134

**Comment by dnkemper** [comment]
Note: unpublish so they still have access to content, but not visible to public

**Comment by richardbporter** [comment]
I think we should also:

- [ ]  remove permission for users to create news so editors/webmaster don't use it by mistake.
- [ ] Disable the blog view
- [ ] Remove main menu link to blog view (disabling might do this automatically)
